kind: pipeline
type: docker
name: hello-world

steps:
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io file 1
    repo: ibalagula2/docker-hello-world-2
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
